version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - customer-service
      - menu-service
      - order-service
      - payment-service
      - inventory-service
    networks:
      - cafe-network

  customer-service:
    build:
      context: ./customer-services
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    networks:
      - cafe-network

  menu-service:
    build:
      context: ./menu-services
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - cafe-network

  order-service:
    build:
      context: ./order-services
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    networks:
      - cafe-network

  payment-service:
    build:
      context: ./payment-services
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    networks:
      - cafe-network

  inventory-service:
    build:
      context: ./inventory-services
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    networks:
      - cafe-network

  mongodb:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db
    networks:
      - cafe-network

networks:
  cafe-network:
    driver: bridge

volumes:
  mongo-data:
